cmake_minimum_required(VERSION 2.8.3)
project(snn_lockstep)
add_compile_options(-std=c++11)
find_package(catkin REQUIRED COMPONENTS roscpp geometry_msgs sensor_msgs std_srvs
  control_toolbox gazebo_ros wind_current water_current message_generation)
find_package(gazebo REQUIRED)
add_service_files(FILES Step.srv SetSail.srv)
generate_messages(DEPENDENCIES geometry_msgs sensor_msgs)
catkin_package(CATKIN_DEPENDS message_runtime roscpp geometry_msgs sensor_msgs)
include_directories(${catkin_INCLUDE_DIRS} ${GAZEBO_INCLUDE_DIRS} vendor/include)
link_directories(${GAZEBO_LIBRARY_DIRS})
add_library(snn_step_plugin SHARED step_plugin.cpp vendor/freefloating_pids.cpp vendor/freefloating_pids_joint.cpp)
add_library(snn_foil_dynamics_plugin SHARED vendor/foil_dynamics_plugin.cpp)
foreach(target snn_step_plugin snn_foil_dynamics_plugin)
  add_dependencies(${target} ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
  target_link_libraries(${target} ${catkin_LIBRARIES} ${GAZEBO_LIBRARIES})
endforeach()
